[package]
name = "mygit-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "mygit_core"
path = "src/lib.rs"

[[bin]]
name = "mygit_core"
path = "src/main.rs"

[dependencies]
sha1 = "0.10.5"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
